### ISSUE TITLE
Errors due to Mocha versioning

### ISSUE THREAD

**Issue by ScottFreeCode** [cades/respec-given#2]
If I npm install both respec-given and Mocha, I always get "Uncaught error outside test suite". I believe this is because NPM puts Respec-Given's Mocha dependency inside Respec-Given's node_modules folder in order to put the manually installed Mocha in the main node_modules folder, so the Mocha that Node finds when Respec-Given `require`s it and the Mocha that is used to run through node_modules/.bin/mocha are actually two different copies.

It may be more appropriate to list Mocha as a peer dependency rather than a regular dependency, since peer dependencies are intended for packages that are addons or plugins for their peer dependency and since it will require the user to separately have installed a compatible Mocha version rather than allowing them to separately install an incompatible version that creates this scenario.

**Comment by cades** [comment]
@ScottFreeCode thanks for point this out! I tried to remove dependency & devDependency, however, the error still occurs. Suddenly I found that is because I use global installed mocha command, not `node_modules/.bin/mocha`. If one of global version and local version of mocha is above 2.4.5 and the other is below 2.4.5, I get an error.

When global > 2.4.5 & local < 2.4.5, I get

`Uncaught error outside test suite`

When global < 2.4.5 & local > 2.4.5, I get

`TypeError: this.parent.isPending is not a function`

When both global & local are below or above 2.4.5, it's OK.

But as an interface developer, we cannot control what version user global installed, so we have 2 options:
1. recommend them use `node_modules/.bin/mocha` instead of `mocha` in command line.
2. detect mocha version in our interface program and handle the difference between versions.

**Comment by cades** [comment]
@ScottFreeCode  Here's the [monkey patch code](https://github.com/cades/respec-given/blob/master/mocha/patch-for-version-inconsistency.js) for the issue. You can try respec-given@0.0.7, it can handle  both version inconsistency cases I memtioned above.

**Comment by cades** [comment]
close this issue since mocha is already listed in `peerDependencies`.
